name: Build README
on:
  push:
    branches:
    - main
    paths-ignore:
    - README.md
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        # necessary for github-action-til-autoformat-readme
        fetch-depth: 0
    - name: Autoformat README
      uses: cflynn07/github-action-til-autoformat-readme@1.2.0
      with:
        description: |
          Inspired by [others](https://github.com/jbranchaud/til) I've [seen](https://github.com/simonw/til) [do this](https://til.hashrocket.com/) and by the idea of [Learning in public](https://dev.to/jbranchaud/how-i-built-a-learning-machine-45k9), I've created this repo to share TILs (Today I learned).
          I'm hoping this will motivate me to more consistently post things so feel free to poke me if it's been a while.
          I've been doing web dev for over a decade and still feel like I'm regularly learning things I "should have known" so hopefully this serves as a reminder that we're all just constantly learning.
        list_most_recent: 2
